# Redis 데이터베이스를 위한 Service 정의 (클러스터 내부 통신용)
apiVersion: v1
kind: Service
metadata:
  name: redis-service # 서비스의 이름 (웹 앱에서 REDIS_HOST로 참조될 이름)
  labels:
    app: redis-db
spec:
  selector:
    app: redis-db # 이 서비스가 트래픽을 전달할 파드를 선택하는 기준 (redis-deployment의 레이블과 일치)
  ports:
    - protocol: TCP
      port: 6379 # 서비스가 노출할 포트 (클러스터 내부에서 접근할 포트)
      targetPort: 6379 # 파드의 컨테이너 포트
  type: ClusterIP # 클러스터 내부에서만 접근 가능하도록 설정 (외부 노출 불필요)