# Redis 데이터베이스를 위한 Deployment 정의
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment # 배포의 이름
  labels:
    app: redis-db # 이 배포에 속하는 파드에 적용될 레이블
spec:
  replicas: 1 # 실행할 파드의 개수
  selector:
    matchLabels:
      app: redis-db # 이 배포가 관리할 파드를 선택하는 기준
  strategy:
    type: Recreate # 볼륨을 사용할 경우 데이터 손실 방지를 위해 Recreate 전략이 유용할 수 있습니다.
  template:
    metadata:
      labels:
        app: redis-db # 파드에 적용될 레이블
    spec:
      containers:
        - name: redis # 컨테이너 이름
          image: redis:latest # Docker Hub에서 최신 Redis 이미지를 사용합니다.
          ports:
            - containerPort: 6379 # Redis 기본 포트
          volumeMounts: # 볼륨 마운트 설정
            - name: redis-data # 아래 정의된 볼륨 이름
              mountPath: /data # Redis가 데이터를 저장하는 컨테이너 내부 경로
      volumes: # 볼륨 정의 (PersistentVolumeClaim을 참조)
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pvc # 아래 정의될 PersistentVolumeClaim의 이름
      restartPolicy: Always
